HTML/HTML/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("htmldjango.urls")),
    path('task/', include("task.urls")),
    path('newyear/', include("newyear.urls"))
]

HTML/htmldjango/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path ("", views.index),
    path ("brian/", views.brian, name = "brian"),
    path ("harry/", views.harry, name = "harry"),
    path ("greet/<str:name>", views.greet, name="greet"),


]

HTML/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path ("", views.newyear, name = "newyear"),

]

HTML/task/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path('', views.index, name ="index" ),
    path("add", views.add, name ="add"),
]

HTML/newyear/models.py
from django.db import models

# Create your models here.

HTML/task/models.py
from django.db import models

# Create your models here.

class NewTaskModels(models.Model):
    task = models.CharField(max_length=200)
    priority = models.IntegerField()

HTML/htmldjango/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request, "htmldjango/index.html")

def brian(request):
    return HttpResponse("hello, brian")

def harry(request):
    return HttpResponse("hello, harry")

def greet(request, name):
    return render(request, "htmldjango/greet.html",{
        "name": name.capitalize()
    })

HTML/newyear/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
# Create your views here.

def newyear(request):
   now = datetime.datetime.now()
   return render(request, "newyear/index.html", {
      "newyear": now.month == 1 and now.day == 1
   })

HTML/task/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import NewTaskModels
from rest_framework.response import Response
# Create your views here.

#tasks = []

#class NewTaskForm(forms.Form):
#    task = forms.CharField(label = "New Task")
#    priority = forms.IntegerField(label = "Priority", min_value=1, max_value=10)


def index(request):
    #if "tasks" not in request.session:
    forms = NewTaskModels.objects.all()
    request.session["text"] = []
    return render(request, "task/index.html", {
        "task": forms
})

def add(request):
    if request.method == "POST":
        #form = NewTaskForm(request.POST)
        #form = NewTaskModels(request.POST)
        remarks = request.POST.get("task")
        remarks2 = request.POST.get("number")
        print("str", remarks)
        forms = NewTaskModels.objects.create(
            task = remarks,
            priority = int(remarks2)
        )
        #return Response(dictionary)
        
        #if form.is_valid():
        #task = form.cleaned_data["task"]
        #request.session["tasks"] += [task]
        #return HttpResponseRedirect(reverse("tasks:index"))
        #else:
         #   return render(request, "task/add.html", {
          #      "form": form
           # })
    return render(request, "task/add.html", {
        #"form": NewTaskForm()
        "form": NewTaskModels()
    })

HTML/htmldjango/templates/htmldjango/greet.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    Hello, {{name}}!
  </body>
</html>

HTML/htmldjango/templates/htmldjango/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Hello, Django</h1>
  </body>
</html>

HTML/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <h3>Is it newyear?</h3>
    {% if newyear %}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
  </body>
</html>

HTML/task/templates/task/add.html
{% extends "task/layout.html" %} {% block body %}
<form action="{% url 'tasks:add' %}" method="POST">
  {% csrf_token %}
  <h1>Add Task</h1>
  {{ form }}
  <input type="text" name="task" />
  <input type="text" name="number" />
  <input type="submit" />
</form>
<a href="{% url 'tasks:index' %}"> Go back </a>
{% endblock %}

HTML/task/templates/task/backup2.tzt.html
{% extends "task/layout.html" %} {% block body %}
<h1 task>List of Task</h1>
<ul>
  {% for taskx in task %}
  <li>{{ taskx }}</li>
  {% empty %}
  <li>No task.</li>
  {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

HTML/task/templates/task/index.html
{% extends "task/layout.html" %} {% block body %}
<h1 task>List of Task</h1>
<ul>
  {% for taskx in task %}
  <li>{{ taskx.task }}</li>
  <li>{{ taskx.priority }}</li>
  {% empty %}
  <li>No task.</li>
  {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

HTML/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block body %} {% endblock %}
  </body>
</html>